Develop
csc/com.servicemesh.agility.adapters.core.aws pull request #15
Opened 2016-09-26 13:33 UTC by sprakash28

@Behnke19 for review
Added Security Group operations with IHttpResponse to handle error scenarios to fix DE2149.

2016-09-26 14:28 UTC, servicemesh-autobuild commented
:x: Build failed

http://ci.servicemesh.com:8080/job/com.servicemesh.agility.adapters.core.aws-prb/11/

2016-09-26 15:47 UTC, Behnke19 requested changes

2016-09-26 15:47 UTC, Behnke19 commented on ivy.xml
> +		<dependency org="com.servicemesh" name="agility.api" rev="getLatestFromBintray(10,2,4)" transitive="false">
There is an easier way to grab the latest. Make the following changes to the ivysettings.xml and ivy.xml files (see attached)
[ivyUpdates.txt](https://github.com/csc/com.servicemesh.agility.adapters.core.aws/files/493324/ivyUpdates.txt)

2016-09-26 18:19 UTC, sprakash28 commented
It seems this pr build is running on java 7

2016-09-26 18:32 UTC, Behnke19 commented
the pr build ran on our agility-java8 build machine. I updated it to be the agility-java8-prb machine to see if that makes a difference

2016-09-26 18:32 UTC, Behnke19 commented
retest

2016-09-26 18:34 UTC, servicemesh-autobuild commented
:x: Build failed

http://ci.servicemesh.com:8080/job/com.servicemesh.agility.adapters.core.aws-prb/12/

2016-09-26 18:43 UTC, Behnke19 commented
retest

2016-09-26 18:49 UTC, servicemesh-autobuild commented
:white_check_mark: Build was successful :tada:


http://ci.servicemesh.com:8080/job/com.servicemesh.agility.adapters.core.aws-prb/13/

2016-09-27 04:58 UTC, servicemesh-autobuild commented
:x: Build failed

http://ci.servicemesh.com:8080/job/com.servicemesh.agility.adapters.core.aws-prb/14/

2016-09-27 04:59 UTC, servicemesh-autobuild commented
:x: Build failed

http://ci.servicemesh.com:8080/job/com.servicemesh.agility.adapters.core.aws-prb/15/

2016-09-27 05:13 UTC, servicemesh-autobuild commented
:white_check_mark: Build was successful :tada:


http://ci.servicemesh.com:8080/job/com.servicemesh.agility.adapters.core.aws-prb/16/

2016-09-27 12:43 UTC, Behnke19 approved these changes

2016-09-27 12:44 UTC, merged